### ISSUE TITLE
Unknown selector type

### ISSUE THREAD

**Issue by ghost** [neurosnap/postcss-scopeify-everything#4]
Encountering this error
```
`unknown` selector type detected for: t_cht
```
which appears to come from [this case](https://github.com/neurosnap/postcss-scopeify-everything/blob/2bd8d9ac893c4bb5dd3f8003fcf5408f344dce81/lib/scopeify-selectors.js#L55).

This is the message causing this problem:
[email_msg.txt](https://github.com/neurosnap/postcss-scopeify-everything/files/1092559/original_msg.txt)

**Comment by neurosnap** [comment]
Thanks for taking the time to post this issue.

Basically this is simply a warning explaining that we cannot process that CSS selector and continue to move onto the next selector, which is exactly what the browser will do as well.

I'd be happy to remove the error if it's just being too noisy, but it should not effect the rest of the processing.

**Comment by ghost** [comment]
in that case, let's just close this then. thanks for explaining 😄
